In [3]:
import numpy as np

def manhattan_distance(state, goal_state):
    distance = 0
    for i in range(3):
        for j in range(3):
            value = state[i][j]
            if value != 0:
                goal_position = np.argwhere(goal_state == value)[0]
                distance += abs(i - goal_position[0]) + abs(j - goal_position[1])
    return distance

def generate_neighbors(state):
    neighbors = []
    for i in range(3):
        for j in range(2):
            neighbor = np.copy(state)
            neighbor[i][j], neighbor[i][j + 1] = neighbor[i][j + 1], neighbor[i][j]
            neighbors.append(neighbor)
        if i < 2:
            for j in range(3):
                neighbor = np.copy(state)
                neighbor[i][j], neighbor[i + 1][j] = neighbor[i + 1][j], neighbor[i][j]
                neighbors.append(neighbor)
    return neighbors

def hill_climbing(initial_state, goal_state):
    current_state = initial_state
    current_distance = manhattan_distance(current_state, goal_state)
    iteration = 0

    while True:
        neighbors = generate_neighbors(current_state)
        best_neighbor = None
        best_distance = current_distance

        for neighbor in neighbors:
            neighbor_distance = manhattan_distance(neighbor, goal_state)
            if neighbor_distance < best_distance:
                best_neighbor = neighbor
                best_distance = neighbor_distance

        iteration += 1
        print(f"\nIteration {iteration}:")
        print(f"Current State (Manhattan Distance: {current_distance}):")
        print(current_state)

        if best_neighbor is None:
            print("\nReached local maximum or goal state:")
            print(current_state)
            return current_state

        current_state = best_neighbor
        current_distance = best_distance

def read_initial_state_from_file(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        state = []
        for line in lines:
            row = list(map(int, line.split()))
            state.append(row)
        return np.array(state)

initial_state = read_initial_state_from_file('initial_state.txt')
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])

solution = hill_climbing(initial_state, goal_state)


Iteration 1:
Current State (Manhattan Distance: 5):
[[3 1 2]
 [6 4 0]
 [7 8 5]]

Iteration 2:
Current State (Manhattan Distance: 4):
[[3 1 2]
 [6 4 5]
 [7 8 0]]

Iteration 3:
Current State (Manhattan Distance: 3):
[[3 1 2]
 [6 4 5]
 [7 0 8]]

Iteration 4:
Current State (Manhattan Distance: 2):
[[3 1 2]
 [6 4 5]
 [0 7 8]]

Iteration 5:
Current State (Manhattan Distance: 1):
[[3 1 2]
 [0 4 5]
 [6 7 8]]

Iteration 6:
Current State (Manhattan Distance: 0):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Reached local maximum or goal state:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
import numpy as np

def hamming_distance(state, goal_state):
    distance = 0
    for i in range(3):
        for j in range(3):
            if state[i][j] != goal_state[i][j] and state[i][j] != 0:
                distance += 1
    return distance

def hill_climbing(initial_state, goal_state):
    current_state = initial_state
    current_distance = hamming_distance(current_state, goal_state)
    iteration = 0

    print(f"Initial State (Hamming Distance: {current_distance}):")
    print(current_state)

    if np.array_equal(current_state, goal_state):
        print("\nInitial state is the goal state.")
        return current_state

    while True:
        neighbors = generate_neighbors(current_state)
        best_neighbor = None
        best_distance = current_distance

        for neighbor in neighbors:
            neighbor_distance = hamming_distance(neighbor, goal_state)
            if neighbor_distance < best_distance:
                best_neighbor = neighbor
                best_distance = neighbor_distance

        iteration += 1
        print(f"\nIteration {iteration}:")
        print(f"Current State (Hamming Distance: {current_distance}):")
        print(current_state)

        if best_neighbor is None:
            print("\nReached local maximum or goal state:")
            print(current_state)
            return current_state

        current_state = best_neighbor
        current_distance = best_distance

        if np.array_equal(current_state, goal_state):
            print("\nGoal state reached.")
            return current_state

def generate_neighbors(state):
    neighbors = []
    for i in range(3):
        for j in range(2):
            neighbor = np.copy(state)
            neighbor[i][j], neighbor[i][j + 1] = neighbor[i][j + 1], neighbor[i][j]
            neighbors.append(neighbor)
        if i < 2:
            for j in range(3):
                neighbor = np.copy(state)
                neighbor[i][j], neighbor[i + 1][j] = neighbor[i + 1][j], neighbor[i][j]
                neighbors.append(neighbor)
    return neighbors

def read_initial_state_from_file(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        state = []
        for line in lines:
            row = list(map(int, line.split()))
            state.append(row)
        return np.array(state)

initial_state = read_initial_state_from_file('initial_state.txt')
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])

solution = hill_climbing(initial_state, goal_state)

Initial State (Hamming Distance: 6):
[[1 2 0]
 [4 3 6]
 [5 7 8]]

Iteration 1:
Current State (Hamming Distance: 6):
[[1 2 0]
 [4 3 6]
 [5 7 8]]

Iteration 2:
Current State (Hamming Distance: 4):
[[1 2 0]
 [3 4 6]
 [5 7 8]]

Iteration 3:
Current State (Hamming Distance: 3):
[[2 1 0]
 [3 4 6]
 [5 7 8]]

Reached local maximum or goal state:
[[2 1 0]
 [3 4 6]
 [5 7 8]]
