In [1]:
import numpy as np
import random
import math

goal_state = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

def read_initial_state(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        initial_state = np.array([list(map(int, line.split())) for line in lines])
    return initial_state

def manhattan_distance(state, goal):
    distance = 0
    for i in range(1, 9):
        current_pos = np.argwhere(state == i)[0]
        goal_pos = np.argwhere(goal == i)[0]
        distance += abs(current_pos[0] - goal_pos[0]) + abs(current_pos[1] - goal_pos[1])
    return distance

def generate_neighbor(state):
    empty_pos = np.argwhere(state == 0)[0]
    possible_moves = []

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for move in moves:
        new_pos = empty_pos + move
        if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
            possible_moves.append(new_pos)

    move = random.choice(possible_moves)

    new_state = np.copy(state)
    new_state[empty_pos[0], empty_pos[1]], new_state[move[0], move[1]] = new_state[move[0], move[1]], new_state[empty_pos[0], empty_pos[1]]
    
    return new_state

def simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold):
    current_state = initial_state
    current_distance = manhattan_distance(current_state, goal_state)
    
    while T > threshold:
        new_state = generate_neighbor(current_state)
        new_distance = manhattan_distance(new_state, goal_state)
        
        delta_E = new_distance - current_distance

        if delta_E < 0 or random.random() < math.exp(-delta_E / T):
            current_state = new_state
            current_distance = new_distance
        
        T *= cooling_rate
    
    return current_state

filename = 'initial_state.txt'
initial_state = read_initial_state(filename)

T = 1000.0
cooling_rate = 0.995
threshold = 1e-3

solution = simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold)

print("Final state after Simulated Annealing:")
print(solution)
print(f"Manhattan Distance from the goal: {manhattan_distance(solution, goal_state)}")

Final state after Simulated Annealing:
[[2 1 8]
 [0 7 3]
 [6 4 5]]
Manhattan Distance from the goal: 9


In [3]:
import numpy as np
import random
import math

goal_state = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

def read_initial_state(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        initial_state = np.array([list(map(int, line.split())) for line in lines])
    return initial_state

def manhattan_distance(state, goal):
    distance = 0
    for i in range(1, 9):
        current_pos = np.argwhere(state == i)[0]
        goal_pos = np.argwhere(goal == i)[0]
        distance += abs(current_pos[0] - goal_pos[0]) + abs(current_pos[1] - goal_pos[1])
    return distance

def hamming_distance(state, goal):
    return np.sum(state != goal) - 1

def generate_neighbor(state):
    empty_pos = np.argwhere(state == 0)[0]
    possible_moves = []

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for move in moves:
        new_pos = empty_pos + move
        if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
            possible_moves.append(new_pos)

    move = random.choice(possible_moves)

    new_state = np.copy(state)
    new_state[empty_pos[0], empty_pos[1]], new_state[move[0], move[1]] = new_state[move[0], move[1]], new_state[empty_pos[0], empty_pos[1]]
    
    return new_state

def simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="manhattan"):
    current_state = initial_state
    iterations = 0

    if distance_metric == "manhattan":
        current_distance = manhattan_distance(current_state, goal_state)
    elif distance_metric == "hamming":
        current_distance = hamming_distance(current_state, goal_state)
    else:
        raise ValueError("Unknown distance metric!")

    while T > threshold:
        iterations += 1

        new_state = generate_neighbor(current_state)

        if distance_metric == "manhattan":
            new_distance = manhattan_distance(new_state, goal_state)
        elif distance_metric == "hamming":
            new_distance = hamming_distance(new_state, goal_state)

        delta_E = new_distance - current_distance

        if delta_E < 0 or random.random() < math.exp(-delta_E / T):
            current_state = new_state
            current_distance = new_distance

        T *= cooling_rate

    return current_state, iterations

filename = 'initial_state.txt'
initial_state = read_initial_state(filename)

T = 1000.0  # Initial temperature
cooling_rate = 0.995  # Cooling rate
threshold = 1e-3  # Stopping temperature

solution_manhattan, iterations_manhattan = simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="manhattan")

solution_hamming, iterations_hamming = simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="hamming")

print("Final state after Simulated Annealing (Manhattan Distance):")
print(solution_manhattan)
print(f"Manhattan Distance from the goal: {manhattan_distance(solution_manhattan, goal_state)}")
print(f"Total iterations (Manhattan Distance): {iterations_manhattan}\n")

print("Final state after Simulated Annealing (Hamming Distance):")
print(solution_hamming)
print(f"Hamming Distance from the goal: {hamming_distance(solution_hamming, goal_state)}")
print(f"Total iterations (Hamming Distance): {iterations_hamming}")

Final state after Simulated Annealing (Manhattan Distance):
[[4 1 2]
 [3 6 5]
 [0 7 8]]
Manhattan Distance from the goal: 4
Total iterations (Manhattan Distance): 2757

Final state after Simulated Annealing (Hamming Distance):
[[8 1 4]
 [2 6 5]
 [3 7 0]]
Hamming Distance from the goal: 5
Total iterations (Hamming Distance): 2757


In [4]:
import numpy as np
import random
import math

# Set random seed for reproducibility
random.seed(50)
np.random.seed(50)

goal_state = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

def read_initial_state(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        initial_state = np.array([list(map(int, line.split())) for line in lines])
    return initial_state

def manhattan_distance(state, goal):
    distance = 0
    for i in range(1, 9):
        current_pos = np.argwhere(state == i)[0]
        goal_pos = np.argwhere(goal == i)[0]
        distance += abs(current_pos[0] - goal_pos[0]) + abs(current_pos[1] - goal_pos[1])
    return distance

def hamming_distance(state, goal):
    return np.sum(state != goal) - 1

def generate_neighbor(state):
    empty_pos = np.argwhere(state == 0)[0]
    possible_moves = []

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for move in moves:
        new_pos = empty_pos + move
        if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:  # Valid position
            possible_moves.append(new_pos)

    move = random.choice(possible_moves)

    new_state = np.copy(state)
    new_state[empty_pos[0], empty_pos[1]], new_state[move[0], move[1]] = new_state[move[0], move[1]], new_state[empty_pos[0], empty_pos[1]]
    
    return new_state

def simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="manhattan"):
    current_state = initial_state
    iterations = 0

    if distance_metric == "manhattan":
        current_distance = manhattan_distance(current_state, goal_state)
    elif distance_metric == "hamming":
        current_distance = hamming_distance(current_state, goal_state)
    else:
        raise ValueError("Unknown distance metric!")

    while T > threshold:
        iterations += 1
        new_state = generate_neighbor(current_state)
        if distance_metric == "manhattan":
            new_distance = manhattan_distance(new_state, goal_state)
        elif distance_metric == "hamming":
            new_distance = hamming_distance(new_state, goal_state)

        delta_E = new_distance - current_distance

        if delta_E < 0 or random.random() < math.exp(-delta_E / T):
            current_state = new_state
            current_distance = new_distance

        T *= cooling_rate

    return current_state, iterations

filename = 'initial_state.txt'
initial_state = read_initial_state(filename)

T = 1000.0
cooling_rate = 0.999
threshold = 1e-3

solution_manhattan, iterations_manhattan = simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="manhattan")

solution_hamming, iterations_hamming = simulated_annealing_puzzle(initial_state, goal_state, T, cooling_rate, threshold, distance_metric="hamming")

print("Final state after Simulated Annealing (Manhattan Distance):")
print(solution_manhattan)
print(f"Manhattan Distance from the goal: {manhattan_distance(solution_manhattan, goal_state)}")
print(f"Total iterations (Manhattan Distance): {iterations_manhattan}\n")

print("Final state after Simulated Annealing (Hamming Distance):")
print(solution_hamming)
print(f"Hamming Distance from the goal: {hamming_distance(solution_hamming, goal_state)}")
print(f"Total iterations (Hamming Distance): {iterations_hamming}")


Final state after Simulated Annealing (Manhattan Distance):
[[2 1 0]
 [3 4 8]
 [6 7 5]]
Manhattan Distance from the goal: 4
Total iterations (Manhattan Distance): 13809

Final state after Simulated Annealing (Hamming Distance):
[[0 1 6]
 [3 4 5]
 [7 2 8]]
Hamming Distance from the goal: 2
Total iterations (Hamming Distance): 13809
